In [2]:
import numpy as np

In [3]:
#BroadCasting

In [4]:
a=[2,2,2]
b=[1,2,3]
c=[]
for i in range(len(b)):
    c.append(a[i]*b[i])

In [5]:
c

[2, 4, 6]

In [6]:
#Here we need to have equal sized arrays so that we can do a scalar multiplicaton like 2*b 

In [7]:
b=np.array(b)

In [8]:
b*2         #Here because of broadcasting we can do this internally is does [2,2,2] * [1,2,3]

array([2, 4, 6])

In [9]:
a=[1,2,3,4]
b=[1,2]
a=np.array(a)
b=np.array(b)
#print(a+b)                      #Here we can not do broadcasting as the shapes of array differ

In [10]:
b=np.array(1)
print(a+b)               #Here This is possible a b is of single dimension(1)

[2 3 4 5]


In [11]:
b

array(1)

In [12]:
print(b)

1


In [13]:
b=[1,2,3,4]
print(a+b)       #here also it is possible as the dimensions are equal here

[2 4 6 8]


In [14]:
a=np.array([[1],[2]])

In [15]:
print(a)

[[1]
 [2]]


In [16]:
a.shape

(2, 1)

In [17]:
a.ndim

2

In [18]:
b=np.array([[1,2,1],[2,3,1],[3,4,1]])

In [19]:
b

array([[1, 2, 1],
       [2, 3, 1],
       [3, 4, 1]])

In [20]:
#a+b

In [21]:
b+a

ValueError: operands could not be broadcast together with shapes (3,3) (2,1) 

In [27]:
b.shape

(3, 3)

In [29]:
a=np.array([[1],[2],[3]])

In [37]:
a.shape

(3, 1)

In [31]:
b=np.array([1,2,3,4])

In [33]:
a+b

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [35]:
b+a

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])