In [1]:
import numpy as np

In [3]:
#Indexing and slicing

In [5]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [7]:
arr[0]

1

In [15]:
arr[0:12]          # here even if the stop value is out of bound it will not result in any error

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
ls=[1,2,3]

In [23]:
ls[0:5]

[1, 2, 3]

In [21]:
arr[12]     #this will result in error

IndexError: index 12 is out of bounds for axis 0 with size 9

In [25]:
arr=np.array([[1,2,3],[2,3,4],[4,5,6]])

In [27]:
arr

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [43]:
arr[0][2]

3

In [45]:
arr[0:1,:2]

array([[1, 2]])

In [49]:
arr[:,0]

array([1, 2, 4])

In [51]:
arr[0,:]

array([1, 2, 3])

In [57]:
arr[0:1,2:]

array([[3]])

In [89]:
arr[0:,::-1]

array([[3, 2, 1],
       [4, 3, 2],
       [6, 5, 4]])

In [91]:
# Boolean indexing used in ml and ds for data filterring efficiently

In [97]:
arr=np.array([10,30,25,50,60])

In [103]:
arr>25

array([False,  True, False,  True,  True])

In [105]:
arr[arr>25]     #Conditional or boolean filtering

array([30, 50, 60])

In [107]:
arr=np.array([[1,3,2],[9,7,8],[5,3,2]])

In [109]:
arr

array([[1, 3, 2],
       [9, 7, 8],
       [5, 3, 2]])

In [115]:
a1=arr[0]

In [117]:
a1[a1>4]

array([], dtype=int32)

In [119]:
view=arr[0:2,0:2]

In [121]:
view

array([[1, 3],
       [9, 7]])

In [123]:
view[0,0]=32          #Its a view changes done here are directly done to original array

In [125]:
arr                              

array([[32,  3,  2],
       [ 9,  7,  8],
       [ 5,  3,  2]])

In [127]:
view1=arr[0:2,0:2].copy()

In [129]:
view1

array([[32,  3],
       [ 9,  7]])

In [131]:
view1[0,1]=21            #here this will not modify the original array as here we have made got a new memory location to store the data

In [133]:
arr

array([[32,  3,  2],
       [ 9,  7,  8],
       [ 5,  3,  2]])

In [135]:
#advanced indexing

In [137]:
arr=np.array([1,2,3,4,5,6])

In [141]:
arr[np.array([2,4,5])]

array([3, 5, 6])

In [143]:
indx_exct=[1,5,4]
arr[indx_exct]

array([2, 6, 5])

In [145]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [147]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [159]:
y=np.array([[0],[2]])

In [161]:
arr[y]

array([[[1, 2, 3]],

       [[7, 8, 9]]])