In [1]:
import numpy as np

In [3]:
#Aggregation functions in numpy

In [5]:
arr=np.array([1,2,3,4,5,6])

In [7]:
arr.sum()

21

In [9]:
arr.min()

1

In [11]:
arr.max()

6

In [33]:
m=arr.mean()

In [19]:
arr.prod()

720

In [23]:
np.median(arr)

3.5

In [27]:
np.std(arr)

1.707825127659933

In [56]:


def std_dev(mean,arr):      #Internally numpy.std is designed like this but i uses vectorization and is efficient for large amount of data
    ans=0
    for num in arr:
        n=arr.size
        vl=(mean-num)*(mean-num)
        vl=vl/n
        ans=ans+vl
    return ans    
an=std_dev(m,arr)       
print(sqrt(an))


        

1.7078251276599332


In [58]:
arr=np.array([[1,2],[3,4]])

In [60]:
arr

array([[1, 2],
       [3, 4]])

In [62]:
np.sum(arr,axis=0)

array([4, 6])

In [64]:
np.sum(arr,axis=1)

array([3, 7])

In [66]:
np.mean(arr,axis=0)

array([2., 3.])

In [68]:
np.sum(arr)

10

In [78]:
#Simple pythonic way to normalize features
def norm(arr):
    mean = np.mean(arr)
    std = np.std(arr)

    normalized = []

    for nm in arr:
        z = (nm - mean) / std
        normalized.append(z)

    return np.array(normalized)   

In [80]:
norm(arr)

array([[-1.34164079, -0.4472136 ],
       [ 0.4472136 ,  1.34164079]])

In [82]:
# Numpy vectorized way to normalize features
def norm(arr):
    mean = np.mean(arr)
    std = np.std(arr)
    return (arr - mean) / std

In [84]:
norm(arr)

array([[-1.34164079, -0.4472136 ],
       [ 0.4472136 ,  1.34164079]])

In [86]:
#Normalizing each cilumn separately

In [98]:
arr=np.array([[170,65],
             [180,72],
             [160,55]])
arr

array([[170,  65],
       [180,  72],
       [160,  55]])

In [104]:
def norm_col(arr):
    mean_cols=np.mean(arr,axis=0)
    std_devcols=np.std(arr,axis=0)
    col1=arr[:,0]
    col2=arr[:,1]
    col1=(col1-mean_cols[0])/std_devcols[0]
    col2=(col2-mean_cols[1])/std_devcols[1]
    arr[:,0]=col1
    arr[:,1]=col2
norm_col(arr)    
#A very brute and inefficient code

In [106]:
arr

array([[ 0,  0],
       [ 1,  1],
       [-1, -1]])

In [108]:
def norm_col(arr):
    mean = np.mean(arr, axis=0)
    std = np.std(arr, axis=0)
    normalized = (arr - mean) / std
    return normalized

In [110]:
norm_col(arr)     #This here uses broadcasting and vecorization correctly

array([[ 0.        ,  0.        ],
       [ 1.22474487,  1.22474487],
       [-1.22474487, -1.22474487]])

In [116]:
arr=np.array([0,1,2,3,4,5,6,7,8,10])

In [122]:
np.reshape(arr,(5,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8, 10]])

In [124]:
np.reshape(arr,(-1,1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [10]])

In [128]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10])

In [142]:
x=np.array([[1],
           [2],
           [3]])

In [144]:
#Calculating norm of vector

In [148]:
np.matmul(x.T,x) 

array([[14]])